name: Git Docker Workshop
on:
  release:
    types: [published] 

jobs:
  Full_Workflow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout tag
      uses: actions/checkout@v3
      with:
        ref: ${{github.ref_name}}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        token: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sa54_randnum_asgnmnt:${{ github.ref_name }}
    - name: Send Notification to slack
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: |
          {
            "text": "SA54 Test Submission",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Name: ${{secrets.SLACK_USERNAME}}\nMatriculation Number: ${{secrets.NUS_MATRICULATION_NUMBER}}\nEmail: ${{secrets.NUS_EMAIL}}\nRepository: ${{ github.repositoryUrl }}\nImage Name: ${{ github.repository }}:${{ github.ref_name }}\nImage URL: ${{secrets.DOCKER_IMAGE_URL}}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
